'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';
import { GoogleTranslator, changeModuleLanguage } from '@/components/GoogleTranslator';

export type Language = 'en' | 'hi' | 'kn' | 'te' | 'ta' | 'mr' | 'bn' | 'gu' | 'ml' | 'or' | 'pa';
export type FontSize = 'normal' | 'large' | 'xlarge';

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  highContrast: boolean;
  toggleHighContrast: () => void;
  fontSize: FontSize;
  setFontSize: (size: FontSize) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    govTitle: 'Ministry of Statistics & Programme Implementation (MoSPI) • SIH Initiative',
    govSubtitle: 'India Official Statistical System (OSS) Skill Intelligence Platform',
    platformName: 'StatPath AI',
    platformTagline: 'AI-Powered Skill Intelligence & Learning Platform',
    navHome: 'Home',
    navAbout: 'About',
    navHowItWorks: 'How It Works',
    navEcosystem: 'Learning Ecosystem',
    navCompetencies: 'Competency Landscape',
    navSecurity: 'Security & Privacy',
    navFaq: 'FAQ',
    navLogin: 'Official Login',
    navRegister: 'Get Started',
    screenReader: 'Screen Reader',
    heroBadge: '🇮🇳 India Official Statistical System • Mission Karmayogi',
    heroTitle: 'Building a Future-Ready Statistical Workforce',
    heroSubhead: 'StatPath AI helps government officials understand their competencies, identify skill gaps and follow personalized learning pathways through India\'s government learning ecosystem.',
    heroCtaPrimary: 'Get Started',
    heroCtaSecondary: 'Explore How It Works',
    whyTitle: 'Why StatPath AI?',
    traditionalLabel: 'Traditional Learning',
    statpathLabel: 'StatPath AI Continuous Intelligence',
    howTitle: '6-Stage Competency Lifecycle',
    step1: 'Cadre & Role Mapping',
    step2: 'Adaptive Competency Assessment',
    step3: 'Skill Deficiency Analysis',
    step4: 'Sequenced iGOT Pathway',
    step5: 'Targeted Micro-Learning',
    step6: 'Continuous Validation & Growth',
    greeting: 'Good morning, Vamshi',
    dashboardOverview: 'Here is your continuous learning and competency overview.',
    competencyScore: 'Competency Score',
    skillReadiness: 'Skill Readiness',
    learningProgress: 'Learning Progress',
    learningTime: 'Learning Time',
    todaysLearning: 'Today\'s Learning',
    todaysSkillByte: 'Today\'s Skill Byte',
    skillDNA: 'Your Skill DNA',
    careerReadiness: 'Where Can Your Skills Take You?',
    startLearning: 'Start Learning',
    tryQuiz: 'Try Quick Quiz',
    viewDetails: 'View Details',
    back: 'Back',
    save: 'Save Changes',
    loading: 'Processing...',
  },
  hi: {
    govTitle: 'सांख्यिकी और कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI) • SIH पहल',
    govSubtitle: 'भारत आधिकारिक सांख्यिकीय प्रणाली (OSS) कौशल बुद्धिमत्ता मंच',
    platformName: 'स्टैटपाथ AI',
    platformTagline: 'एआई-संचालित कौशल बुद्धिमत्ता और शिक्षण मंच',
    navHome: 'मुख्य पृष्ठ',
    navAbout: 'हमारे बारे में',
    navHowItWorks: 'यह कैसे काम करता है',
    navEcosystem: 'शिक्षण पारिस्थितिकी तंत्र',
    navCompetencies: 'क्षमता परिदृश्य',
    navSecurity: 'सुरक्षा और गोपनीयता',
    navFaq: 'अक्सर पूछे जाने वाले प्रश्न',
    navLogin: 'आधिकारिक लॉगिन',
    navRegister: 'प्रारंभ करें',
    screenReader: 'स्क्रीन रीडर',
    heroBadge: '🇮🇳 भारत आधिकारिक सांख्यिकीय प्रणाली • मिशन कर्मयोगी',
    heroTitle: 'भविष्य के लिए तैयार सांख्यिकीय कार्यबल का निर्माण',
    heroSubhead: 'स्टैटपाथ AI सरकारी अधिकारियों को अपनी क्षमताओं को समझने, कौशल अंतर की पहचान करने और भारत के शिक्षण पारिस्थितिकी तंत्र का पालन करने में मदद करता है।',
    heroCtaPrimary: 'प्रारंभ करें',
    heroCtaSecondary: 'कार्यप्रणाली देखें',
    whyTitle: 'स्टैटपाथ AI क्यों?',
    traditionalLabel: 'पारंपरिक शिक्षा',
    statpathLabel: 'स्टैटपाथ AI निरंतर बुद्धिमत्ता',
    howTitle: '६-चरण क्षमता यात्रा',
    step1: 'मुझे समझें',
    step2: 'मेरे कौशल का मूल्यांकन करें',
    step3: 'मेरी कमियों की पहचान करें',
    step4: 'मेरा शिक्षण पथ बनाएं',
    step5: 'सीखें और अभ्यास करें',
    step6: 'निरंतर सुधार करें',
    greeting: 'शुभ प्रभात, वंशी',
    dashboardOverview: 'यहाँ आपकी निरंतर सीखने और क्षमता का अवलोकन है।',
    competencyScore: 'क्षमता स्कोर',
    skillReadiness: 'कौशल तत्परता',
    learningProgress: 'शिक्षण प्रगति',
    learningTime: 'शिक्षण समय',
    todaysLearning: 'आज की सीख',
    todaysSkillByte: 'आज का कौशल बाइट',
    skillDNA: 'आपका कौशल डीएनए',
    careerReadiness: 'आपके कौशल आपको कहाँ ले जा सकते हैं?',
    startLearning: 'सीखना शुरू करें',
    tryQuiz: 'त्वरित प्रश्नोत्तरी आजमाएं',
    viewDetails: 'विवरण देखें',
    back: 'वापस',
    save: 'परिवर्तन सहेजें',
    loading: 'प्रक्रिया जारी है...',
  },
  kn: {
    govTitle: 'ಸಾಂಖ್ಯಿಕ ಮತ್ತು ಕಾರ್ಯಕ್ರಮ ಅನುಷ್ಠಾನ ಸಚಿವಾಲಯ (MoSPI) • SIH ಯೋಜನೆ',
    govSubtitle: 'ಭಾರತೀಯ ಅಧಿಕೃತ ಸಾಂಖ್ಯಿಕ ವ್ಯವಸ್ಥೆ (OSS) ಕೌಶಲ್ಯ ಪೋರ್ಟಲ್',
    platformName: 'ಸ್ಟ್ಯಾಟ್‌ಪಾಥ್ AI',
    platformTagline: 'ಎಐ-ಚಾಲಿತ ಕೌಶಲ್ಯ ಬುದ್ಧಿವಂತಿಕೆ ಮತ್ತು ಕಲಿಕೆಯ ವೇದಿಕೆ',
    navHome: 'ಮುಖ್ಯ ಪುಟ',
    navAbout: 'ನಮ್ಮ ಬಗ್ಗೆ',
    navHowItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    navEcosystem: 'ಕಲಿಕಾ ವ್ಯವಸ್ಥೆ',
    navCompetencies: 'ಸಾಮರ್ಥ್ಯ ವಲಯ',
    navSecurity: 'ಸುರಕ್ಷತೆ ಮತ್ತು ಗೌಪ್ಯತೆ',
    navFaq: 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    navLogin: 'ಅಧಿಕೃತ ಲಾಗಿನ್',
    navRegister: 'ಪ್ರಾರಂಭಿಸಿ',
    screenReader: 'ಸ್ಕ್ರೀನ್ ರೀಡರ್',
    heroBadge: '🇮🇳 ಭಾರತೀಯ ಅಧಿಕೃತ ಸಾಂಖ್ಯಿಕ ವ್ಯವಸ್ಥೆ • ಮಿಷನ್ ಕರ್ಮಯೋಗಿ',
    heroTitle: 'ಭವಿಷ್ಯಕ್ಕೆ ಸಿದ್ಧವಿರುವ ಸಾಂಖ್ಯಿಕ ಕಾರ್ಯಪಡೆಯ ನಿರ್ಮಾಣ',
    heroSubhead: 'ಸ್ಟ್ಯಾಟ್‌ಪಾಥ್ AI ಸರ್ಕಾರಿ ಅಧಿಕಾರಿಗಳಿಗೆ ತಮ್ಮ ಸಾಮರ್ಥ್ಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು, ಕೌಶಲ್ಯ ಕೊರತೆಗಳನ್ನು ಗುರುತಿಸಲು ಮತ್ತು ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಕಲಿಕೆಯ ಹಾದಿಯನ್ನು ಅನುಸರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    heroCtaPrimary: 'ಪ್ರಾರಂಭಿಸಿ',
    heroCtaSecondary: 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ನೋಡಿ',
    whyTitle: 'ಏಕೆ ಸ್ಟ್ಯಾಟ್‌ಪಾಥ್ AI?',
    traditionalLabel: 'ಸಾಂಪ್ರದಾಯಿಕ ಕಲಿಕೆ',
    statpathLabel: 'ಸ್ಟ್ಯಾಟ್‌ಪಾಥ್ AI ನಿರಂತರ ಬುದ್ಧಿವಂತಿಕೆ',
    howTitle: '೬-ಹಂತದ ಸಾಮರ್ಥ್ಯ ಪ್ರಯಾಣ',
    step1: 'ನನ್ನನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',
    step2: 'ನನ್ನ ಕೌಶಲ್ಯ ಮೌಲ್ಯಮಾಪನ',
    step3: 'ನನ್ನ ಕುಂದುಕೊರತೆ ಗುರುತಿಸಿ',
    step4: 'ನನ್ನ ಕಲಿಕಾ ಹಾದಿ ನಿರ್ಮಿಸಿ',
    step5: 'ಕಲಿಯಿರಿ ಮತ್ತು ಅಭ್ಯಾಸ ಮಾಡಿ',
    step6: 'ನಿರಂತರವಾಗಿ ಸುಧಾರಿಸಿ',
    greeting: 'ಶುಭೋದಯ, ವಂಶಿ',
    dashboardOverview: 'ಇಲ್ಲಿ ನಿಮ್ಮ ನಿರಂತರ ಕಲಿಕೆ ಮತ್ತು ಸಾಮರ್ಥ್ಯದ ಅವಲೋಕನವಿದೆ.',
    competencyScore: 'ಸಾಮರ್ಥ್ಯ ಸ್ಕೋರ್',
    skillReadiness: 'ಕೌಶಲ್ಯ ಸಿದ್ಧತೆ',
    learningProgress: 'ಕಲಿಕೆಯ ಪ್ರಗತಿ',
    learningTime: 'ಕಲಿಕೆಯ ಸಮಯ',
    todaysLearning: 'ಇಂದಿನ ಕಲಿಕೆ',
    todaysSkillByte: 'ಇಂದಿನ ಕೌಶಲ್ಯ ತುಣುಕು',
    skillDNA: 'ನಿಮ್ಮ ಕೌಶಲ್ಯ DNA',
    careerReadiness: 'ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳು ನಿಮ್ಮನ್ನು ಎಲ್ಲಿಗೆ ಕೊಂಡೊಯ್ಯಬಲ್ಲವು?',
    startLearning: 'ಕಲಿಕೆ ಪ್ರಾರಂಭಿಸಿ',
    tryQuiz: 'ಕ್ವಿಜ್ ಪ್ರಯತ್ನಿಸಿ',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    back: 'ಹಿಂದಕ್ಕೆ',
    save: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    loading: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...',
  },
  te: {
    govTitle: 'సాంఖ్యిక మరియు కార్యక్రమాల అమలు మంత్రిత్వ శాఖ (MoSPI) • SIH చొరవ',
    govSubtitle: 'భారత అధికారిక సాంఖ్యిక వ్యవస్థ (OSS) నైపుణ్య ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్',
    platformName: 'స్టాట్‌పాత్ AI',
    platformTagline: 'AI-ఆధారిత నైపుణ్య ఇంటెలిజెన్స్ & లెర్నింగ్ ప్లాట్‌ఫారమ్',
    navHome: 'హోమ్‌పేజీ',
    navAbout: 'మా గురించి',
    navHowItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    navEcosystem: 'లెర్నింగ్ ఎకోసిస్టమ్',
    navCompetencies: 'సామర్థ్యాల ల్యాండ్‌స్కేప్',
    navSecurity: 'భద్రత & గోప్యత',
    navFaq: 'తరచుగా అడిగే ప్రశ్నలు',
    navLogin: 'అధికారిక లాగిన్',
    navRegister: 'ప్రారంభించండి',
    screenReader: 'స్క్రీన్ రీడర్',
    heroBadge: '🇮🇳 భారత అధికారిక సాంఖ్యిక వ్యవస్థ • మిషన్ కర్మయోగి',
    heroTitle: 'భవిష్యత్తుకు సిద్ధంగా ఉన్న సాంఖ్యిక వర్క్‌ఫోర్స్ నిర్మాణం',
    heroSubhead: 'స్టాట్‌పాత్ AI ప్రభుత్వ అధికారులకు వారి సామర్థ్యాలను అర్థం చేసుకోవడానికి మరియు నైపుణ్య లోపాలను గుర్తించడానికి సహాయపడుతుంది.',
    heroCtaPrimary: 'ప్రారంభించండి',
    heroCtaSecondary: 'ఎలా పనిచేస్తుందో చూడండి',
    whyTitle: 'ఎందుకు స్టాట్‌పాత్ AI?',
    traditionalLabel: 'సాంప్రదాయ నేర్చుకోవడం',
    statpathLabel: 'స్టాట్‌పాత్ AI నిరంతర ఇంటెలిజెన్స్',
    howTitle: '6-దశల సామర్థ్య ప్రయాణం',
    step1: 'నన్ను అర్థం చేసుకోండి',
    step2: 'నా నైపుణ్యాలను అంచనా వేయండి',
    step3: 'నా లోపాలను గుర్తించండి',
    step4: 'నా లెర్నింగ్ పాతను రూపొందించండి',
    step5: 'నేర్చుకోండి & అభ్యసించండి',
    step6: 'నిరంతరం మెరుగుపరచండి',
    greeting: 'శుభోదయం, వంశీ',
    dashboardOverview: 'ఇది మీ నిరంతర నేర్చుకోవడం మరియు సామర్థ్యాల అవలోకనం.',
    competencyScore: 'సామర్థ్య స్కోరు',
    skillReadiness: 'నైపుణ్య సన్నద్ధత',
    learningProgress: 'నేర్చుకునే పురోగతి',
    learningTime: 'నేర్చుకునే సమయం',
    todaysLearning: 'ఈనాటి పాఠం',
    todaysSkillByte: 'ఈనాటి స్కిల్ బైట్',
    skillDNA: 'మీ స్కిల్ DNA',
    careerReadiness: 'మీ నైపుణ్యాలు మిమ్మల్ని ఎక్కడికి తీసుకెళ్లగలవు?',
    startLearning: 'నేర్చుకోవడం ప్రారంభించండి',
    tryQuiz: 'క్విజ్ ప్రయత్నించండి',
    viewDetails: 'వివరాలు చూడండి',
    back: 'వెనుకకు',
    save: 'మార్పులను సేవ్ చేయండి',
    loading: 'ప్రాసెస్ అవుతోంది...',
  },
  ta: {
    govTitle: 'புள்ளியியல் மற்றும் திட்ட அமலாக்க அமைச்சகம் (MoSPI) • SIH முயற்சி',
    govSubtitle: 'இந்திய அதிகாரப்பூர்வ புள்ளியியல் அமைப்பு (OSS) திறன் தளம்',
    platformName: 'ஸ்டாட்பாத் AI',
    platformTagline: 'AI-இயக்கப்பட்ட திறன் நுண்ணறிவு மற்றும் கற்றல் தளம்',
    navHome: 'முகப்பு',
    navAbout: 'எங்களைப் பற்றி',
    navHowItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    navEcosystem: 'கற்றல் சுற்றுச்சூழல்',
    navCompetencies: 'திறன் நிலப்பரப்பு',
    navSecurity: 'பாதுகாப்பு & தனியுரிமை',
    navFaq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    navLogin: 'அதிகாரப்பூர்வ உள்நுழைவு',
    navRegister: 'தொடங்கவும்',
    screenReader: 'திரை வாசிப்பான்',
    heroBadge: '🇮🇳 இந்திய அதிகாரப்பூர்வ புள்ளியியல் அமைப்பு • மிஷன் கர்மயோகி',
    heroTitle: 'எதிர்காலத்திற்குத் தயாரான புள்ளியியல் பணியாளர்களை உருவாக்குதல்',
    heroSubhead: 'ஸ்டாட்பாத் AI அரசு அதிகாரிகளுக்கு அவர்களின் திறன்களைப் புரிந்துகொள்ளவும், இடைவெளிகளைக் கண்டறியவும் உதவுகிறது.',
    heroCtaPrimary: 'தொடங்கவும்',
    heroCtaSecondary: 'செயல்பாட்டை அறியவும்',
    whyTitle: 'ஏன் ஸ்டாட்பாத் AI?',
    traditionalLabel: 'பாரம்பரிய கற்றல்',
    statpathLabel: 'ஸ்டாட்பாத் AI தொடர்ச்சியான நுண்ணறிவு',
    howTitle: '6-படி திறன் பயணம்',
    step1: 'என்னை புரிந்து கொள்ளுங்கள்',
    step2: 'என் திறன்களை மதிப்பிடுங்கள்',
    step3: 'என் இடைவெளிகளைக் கண்டறியவும்',
    step4: 'என் கற்றல் பாதையை உருவாக்குங்கள்',
    step5: 'கற்றுக்கொண்டு பயிற்சி செய்யுங்கள்',
    step6: 'தொடர்ந்து மேம்படுத்துங்கள்',
    greeting: 'காலை வணக்கம், வம்சி',
    dashboardOverview: 'உங்கள் தொடர்ச்சியான கற்றல் மற்றும் திறன் கண்ணோட்டம் இதோ.',
    competencyScore: 'திறன் மதிப்பெண்',
    skillReadiness: 'திறன் தயார்நிலை',
    learningProgress: 'கற்றல் முன்னேற்றம்',
    learningTime: 'கற்றல் நேரம்',
    todaysLearning: 'இன்றைய கற்றல்',
    todaysSkillByte: 'இன்றைய திறன் துண்டு',
    skillDNA: 'உங்கள் திறன் DNA',
    careerReadiness: 'உங்கள் திறன்கள் உங்களை எங்கு கொண்டு செல்லும்?',
    startLearning: 'கற்றலைத் தொடங்குங்கள்',
    tryQuiz: 'வினாடி வினாவை முயலவும்',
    viewDetails: 'விவரங்களைக் காண்க',
    back: 'பின்னால்',
    save: 'மாற்றங்களைச் சேமிக்கவும்',
    loading: 'செயலாக்கப்படுகிறது...',
  },
  mr: {
    govTitle: 'सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय (MoSPI) • SIH पुढाकार',
    govSubtitle: 'भारत अधिकृत सांख्यिकी प्रणाली (OSS) कौशल्य बुद्धिमत्ता मंच',
    platformName: 'स्टॅटपाथ AI',
    platformTagline: 'एआय-संचालित कौशल्य बुद्धिमत्ता आणि शिक्षण मंच',
    navHome: 'मुख्यपृष्ठ',
    navAbout: 'आमच्याबद्दल',
    navHowItWorks: 'हे कसे कार्य करते',
    navEcosystem: 'शिक्षण परिसंस्था',
    navCompetencies: 'क्षमता दृश्य',
    navSecurity: 'सुरक्षा आणि गोपनीयता',
    navFaq: 'सतत विचारले जाणारे प्रश्न',
    navLogin: 'अधिकृत लॉगिन',
    navRegister: 'शुरू करा',
    screenReader: 'स्क्रीन रीडर',
    heroBadge: '🇮🇳 भारत अधिकृत सांख्यिकी प्रणाली • मिशन कर्मयोगी',
    heroTitle: 'भविष्यासाठी तयार सांख्यिकी कार्यबळाची निर्मिती',
    heroSubhead: 'स्टॅटपाथ AI सरकारी अधिकाऱ्यांना त्यांच्या क्षमता समजून घेण्यास आणि कौशल्य तफावत ओळखण्यास मदत करते.',
    heroCtaPrimary: 'शुरू करा',
    heroCtaSecondary: 'प्रक्रिया पहा',
    whyTitle: 'स्टॅटपाथ AI का?',
    traditionalLabel: 'पारंपारिक शिक्षण',
    statpathLabel: 'स्टॅटपाथ AI सतत बुद्धिमत्ता',
    howTitle: '६-टप्प्यांची क्षमता प्रवास',
    step1: 'मला समजून घ्या',
    step2: 'माझ्या कौशल्यांचे मूल्यमापन करा',
    step3: 'माझ्या कमतरता ओळखा',
    step4: 'माझा शिक्षण मार्ग तयार करा',
    step5: 'शिका आणि सराव करा',
    step6: 'सतत सुधारणा करा',
    greeting: 'शुभ सकाळ, वंशी',
    dashboardOverview: 'येथे आपले सतत शिक्षण आणि क्षमता विहंगावलोकन आहे.',
    competencyScore: 'क्षमता स्कोर',
    skillReadiness: 'कौशल्य सज्जता',
    learningProgress: 'शिक्षण प्रगती',
    learningTime: 'शिक्षण वेळ',
    todaysLearning: 'आजचे शिक्षण',
    todaysSkillByte: 'आजचा कौशल्य बाईट',
    skillDNA: 'तुमचे कौशल्य डीएनए',
    careerReadiness: 'तुमचे कौशल्य तुम्हाला कुठे नेऊ शकते?',
    startLearning: 'शिकणे सुरू करा',
    tryQuiz: 'क्विझ प्रयत्न करा',
    viewDetails: 'तपशील पहा',
    back: 'मागे',
    save: 'बदल जतन करा',
    loading: 'प्रक्रिया सुरू आहे...',
  },
  bn: {
    govTitle: 'পরিসংখ্যান ও কর্মসূচি বাস্তবায়ন মন্ত্রক (MoSPI) • SIH উদ্যোগ',
    govSubtitle: 'ভারত সরকারি পরিসংখ্যান ব্যবস্থা (OSS) দক্ষতা প্ল্যাটফর্ম',
    platformName: 'স্ট্যাটপাথ AI',
    platformTagline: 'এআই-চালিত দক্ষতা বুদ্ধিমত্তা ও শিখন প্ল্যাটফর্ম',
    navHome: 'হোম',
    navAbout: 'আমাদের সম্পর্কে',
    navHowItWorks: 'কীভাবে কাজ করে',
    navEcosystem: 'শিখন ইকোসিস্টেম',
    navCompetencies: 'দক্ষতা দৃশ্যপট',
    navSecurity: 'নিরাপত্তা ও গোপনীয়তা',
    navFaq: 'সাধারণ জিজ্ঞাসা',
    navLogin: 'অফিসিয়াল লগইন',
    navRegister: 'শুরু করুন',
    screenReader: 'স্ক্রিন রিডার',
    heroBadge: '🇮🇳 ভারত সরকারি পরিসংখ্যান ব্যবস্থা • মিশন কর্মযোগী',
    heroTitle: 'ভবিষ্যতের জন্য প্রস্তুত পরিসংখ্যানগত কর্মীবাহিনী গঠন',
    heroSubhead: 'স্ট্যাটপাথ AI সরকারি কর্মকর্তাদের তাদের দক্ষতা বুঝতে এবং ঘাটতি চিহ্নিত করতে সহায়তা করে।',
    heroCtaPrimary: 'শুরু করুন',
    heroCtaSecondary: 'কার্যপদ্ধতি দেখুন',
    whyTitle: 'কেন স্ট্যাটপাথ AI?',
    traditionalLabel: 'ঐতিহ্যগত শিক্ষা',
    statpathLabel: 'স্ট্যাটপাথ AI ধারাবাহিক বুদ্ধিমত্তা',
    howTitle: '৬-ধাপের দক্ষতা যাত্রা',
    step1: 'আমাকে বুঝুন',
    step2: 'আমার দক্ষতা মূল্যায়ন করুন',
    step3: 'আমার ঘাটতি চিহ্নিত করুন',
    step4: 'আমার শিখন পথ তৈরি করুন',
    step5: 'শিখুন ও অনুশীলন করুন',
    step6: 'ক্রমাগত উন্নতি করুন',
    greeting: 'শুভ সকাল, বংশী',
    dashboardOverview: 'এখানে আপনার ক্রমাগত শিখন এবং দক্ষতার ওভারভিউ রয়েছে।',
    competencyScore: 'দক্ষতা স্কোর',
    skillReadiness: 'দক্ষতা প্রস্তুতি',
    learningProgress: 'শিখন অগ্রগতি',
    learningTime: 'শিখন সময়',
    todaysLearning: 'আজকের শিক্ষা',
    todaysSkillByte: 'আজকের স্কিল বাইট',
    skillDNA: 'আপনার স্কিল ডিএনএ',
    careerReadiness: 'আপনার দক্ষতা আপনাকে কোথায় নিয়ে যেতে পারে?',
    startLearning: 'শেখা শুরু করুন',
    tryQuiz: 'কুইজ চেষ্টা করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    back: 'ফিরে যান',
    save: 'পরিবর্তন সংরক্ষণ করুন',
    loading: 'প্রক্রিয়াধীন...',
  },
  gu: {
    govTitle: 'આંકડાશાસ્ત્ર અને કાર્યક્રમ અમલીકરણ મંત્રાલય (MoSPI) • SIH પહેલ',
    govSubtitle: 'ભારત સત્તાવાર આંકડાકીય પ્રણાલી (OSS) કૌશલ્ય મંચ',
    platformName: 'સ્ટેટપાથ AI',
    platformTagline: 'AI-સંચાલિત કૌશલ્ય બુદ્ધિમત્તા અને શિક્ષણ મંચ',
    navHome: 'મુખ્ય પૃષ્ઠ',
    navAbout: 'અમારા વિશે',
    navHowItWorks: 'તે કેવી રીતે કામ કરે છે',
    navEcosystem: 'શિક્ષણ ઇકોસિસ્ટમ',
    navCompetencies: 'ક્ષમતા પરિદ્રશ્ય',
    navSecurity: 'સુરક્ષા અને ગોપનીયતા',
    navFaq: 'વારંવાર પૂછાતા પ્રશ્નો',
    navLogin: 'સત્તાવાર લૉગિન',
    navRegister: 'શરૂ કરો',
    screenReader: 'સ્ક્રીન રીડર',
    heroBadge: '🇮🇳 ભારત સત્તાવાર આંકડાકીય પ્રણાલી • મિશન કર્મયોગી',
    heroTitle: 'ભવિષ્ય માટે તૈયાર આંકડાકીય કાર્યબળનું નિર્માણ',
    heroSubhead: 'સ્ટેટપાથ AI સરકારી અધિકારીઓને તેમની ક્ષમતાઓ સમજવામાં અને કૌશલ્ય તફાવત ઓળખવામાં મદદ કરે છે.',
    heroCtaPrimary: 'શરૂ કરો',
    heroCtaSecondary: 'કાર્યપદ્ધતિ જુઓ',
    whyTitle: 'શા માટે સ્ટેટપાથ AI?',
    traditionalLabel: 'પરંપરાગત શિક્ષણ',
    statpathLabel: 'સ્ટેટપાથ AI સતત બુદ્ધિમત્તા',
    howTitle: '૬-તબક્કાની ક્ષમતા યાત્રા',
    step1: 'મને સમજો',
    step2: 'મારા કૌશલ્યનું મૂલ્યાંકન કરો',
    step3: 'મારી ખામીઓ ઓળખો',
    step4: 'મારો શિક્ષણ માર્ગ બનાવો',
    step5: 'શીખો અને અભ્યાસ કરો',
    step6: 'સતત સુધારો કરો',
    greeting: 'સુપ્રભાત, વંશી',
    dashboardOverview: 'અહીં તમારું સતત શિક્ષણ અને ક્ષમતાનું વિહંગાવલોકન છે.',
    competencyScore: 'ક્ષમતા સ્કોર',
    skillReadiness: 'કૌશલ્ય તૈયારી',
    learningProgress: 'શિક્ષણ પ્રગતિ',
    learningTime: 'શિક્ષણ સમય',
    todaysLearning: 'આજનું શિક્ષણ',
    todaysSkillByte: 'આજનું કૌશલ્ય બાઇટ',
    skillDNA: 'તમારું કૌશલ્ય ડીએનએ',
    careerReadiness: 'તમારા કૌશલ્યો તમને ક્યાં લઈ જઈ શકે છે?',
    startLearning: 'શીખવાનું શરૂ કરો',
    tryQuiz: 'ક્વિઝ પ્રયાસ કરો',
    viewDetails: 'વિગતો જુઓ',
    back: 'પાછા જાઓ',
    save: 'ફેરફારો સાચવો',
    loading: 'પ્રક્રિયા ચાલુ છે...',
  },
  ml: {
    govTitle: 'സ്ഥിതിവിവരക്കണക്ക് മന്ത്രാലയം (MoSPI) • SIH സംരംഭം',
    govSubtitle: 'ഇന്ത്യ ഔദ്യോഗിക സ്ഥിതിവിവരക്കണക്ക് സിസ്റ്റം (OSS) സ്കിൽ പ്ലാറ്റ്ഫോം',
    platformName: 'സ്റ്റാറ്റ്പാത്ത് AI',
    platformTagline: 'AI-പവേർഡ് സ്കിൽ ഇന്റലിജൻസ് & ലേണിംഗ് പ്ലാറ്റ്‌ഫോം',
    navHome: 'ഹോം',
    navAbout: 'ഞങ്ങളെക്കുറിച്ച്',
    navHowItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    navEcosystem: 'ലേണിംഗ് ഇക്കോസിസ്റ്റം',
    navCompetencies: 'പ്രാവീണ്യ മേഖല',
    navSecurity: 'സുരക്ഷയും സ്വകാര്യതയും',
    navFaq: 'ചോദ്യോത്തരങ്ങൾ',
    navLogin: 'ഔദ്യോഗിക ലോഗിൻ',
    navRegister: 'ആരംഭിക്കുക',
    screenReader: 'സ്ക്രീൻ റീഡർ',
    heroBadge: '🇮🇳 ഇന്ത്യ ഔദ്യോഗിക സ്ഥിതിവിവരക്കണക്ക് സിസ്റ്റം • മിഷൻ കർമ്മയോഗി',
    heroTitle: 'ഭാവിക്ക് സജ്ജമായ സ്റ്റാറ്റിസ്റ്റിക്കൽ വർക്ക്ഫോഴ്സ് നിർമ്മാണം',
    heroSubhead: 'സ്റ്റാറ്റ്പാത്ത് AI ഉദ്യോഗസ്ഥർക്ക് അവരുടെ കഴിവുകൾ മനസ്സിലാക്കാനും കഴിവില്ലായ്മകൾ തിരിച്ചറിയാനും സഹായിക്കുന്നു.',
    heroCtaPrimary: 'ആരംഭിക്കുക',
    heroCtaSecondary: 'പ്രവർത്തനം കാണുക',
    whyTitle: 'എന്തുകൊണ്ട് സ്റ്റാറ്റ്പാത്ത് AI?',
    traditionalLabel: 'പരമ്പരാഗത പഠനം',
    statpathLabel: 'സ്റ്റാറ്റ്പാത്ത് AI തുടർച്ചയായ ഇന്റലിജൻസ്',
    howTitle: '6-ഘട്ട പ്രാവീണ്യ യാത്ര',
    step1: 'എന്നെ മനസ്സിലാക്കൂ',
    step2: 'എന്റെ കഴിവുകൾ വിലയിരുത്തൂ',
    step3: 'എന്റെ പോരായ്മകൾ തിരിച്ചറിയൂ',
    step4: 'എന്റെ പഠന പാത ഉണ്ടാക്കൂ',
    step5: 'പഠിക്കൂ പരിശീലിക്കൂ',
    step6: 'തുടർച്ചയായി മെച്ചപ്പെടൂ',
    greeting: 'സുപ്രഭാതം, വംശി',
    dashboardOverview: 'നിങ്ങളുടെ തുടർച്ചയായ പഠനത്തിന്റെയും പ്രാവീണ്യത്തിന്റെയും അവലോകനം ഇതാ.',
    competencyScore: 'പ്രാവീണ്യ സ്കോർ',
    skillReadiness: 'കഴിവ് സജ്ജത',
    learningProgress: 'പഠന പുരോഗതി',
    learningTime: 'പഠന സമയം',
    todaysLearning: 'ഇന്നത്തെ പഠനം',
    todaysSkillByte: 'ഇന്നത്തെ സ്കിൽ ബൈറ്റ്',
    skillDNA: 'നിങ്ങളുടെ സ്കിൽ DNA',
    careerReadiness: 'നിങ്ങളുടെ കഴിവുകൾ നിങ്ങളെ എവിടെ എത്തിക്കാം?',
    startLearning: 'പഠനം ആരംഭിക്കുക',
    tryQuiz: 'ക്വിസ് ശ്രമിക്കുക',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    back: 'പിന്നോട്ട്',
    save: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    loading: 'പ്രക്രിയയില് ആണ്...',
  },
  or: {
    govTitle: 'ପରିସଂଖ୍ୟାନ ଏବଂ କାର୍ଯ୍ୟକ୍ରମ ରୂପାୟନ ମନ୍ତ୍ରଣାଳୟ (MoSPI) • SIH ପଦକ୍ଷେପ',
    govSubtitle: 'ଭାରତ ସରକାରୀ ପରିସଂଖ୍ୟାନ ପ୍ରଣାଳୀ (OSS) ଦକ୍ଷତା ପ୍ଲାଟଫର୍ମ',
    platformName: 'ଷ୍ଟାଟପାଥ AI',
    platformTagline: 'AI-ଚାଳିତ ଦକ୍ଷତା ବୁଦ୍ଧିମତ୍ତା ଏବଂ ଶିକ୍ଷଣ ପ୍ଲାଟଫର୍ମ',
    navHome: 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    navAbout: 'ଆମ ବିଷୟରେ',
    navHowItWorks: 'ଏହା କିପରି କାମ କରେ',
    navEcosystem: 'ଶିକ୍ଷଣ ଇକୋସିଷ୍ଟମ',
    navCompetencies: 'ଦକ୍ଷତା ଦୃଶ୍ୟପଟ',
    navSecurity: 'ସୁରକ୍ଷା ଏବଂ ଗୋପନୀୟତା',
    navFaq: 'ସାଧାରଣ ପ୍ରଶ୍ନ',
    navLogin: 'ସରକାରୀ ଲଗଇନ୍',
    navRegister: 'ଆରମ୍ଭ କରନ୍ତୁ',
    screenReader: 'ସ୍କ୍ରିନ୍ ରିଡର୍',
    heroBadge: '🇮🇳 ଭାରତ ସରକାରୀ ପରିସଂଖ୍ୟାନ ପ୍ରଣାଳୀ • ମିଶନ କର୍ମଯୋଗୀ',
    heroTitle: 'ଭବିଷ୍ୟତ ପାଇଁ ପ୍ରସ୍ତୁତ ପରିସଂଖ୍ୟାନ କାର୍ଯ୍ୟବଳର ନିର୍ମାଣ',
    heroSubhead: 'ଷ୍ଟାଟପାଥ AI ସରକାରୀ ଅଧିକାରୀଙ୍କୁ ସେମାନଙ୍କର ଦକ୍ଷତା ବୁଝିବାରେ ଏବଂ ଅଭାବ ଚିହ୍ନଟ କରିବାରେ ସାହାଯ୍ୟ କରେ।',
    heroCtaPrimary: 'ଆରମ୍ଭ କରନ୍ତୁ',
    heroCtaSecondary: 'କାର୍ଯ୍ୟପ୍ରଣାଳୀ ଦେଖନ୍ତୁ',
    whyTitle: 'କାହିଁକି ଷ୍ଟାଟପାଥ AI?',
    traditionalLabel: 'ପାରମ୍ପରିକ ଶିକ୍ଷା',
    statpathLabel: 'ଷ୍ଟାଟପାଥ AI ନିରନ୍ତର ବୁଦ୍ଧିମତ୍ତା',
    howTitle: '୬-ପଦକ୍ଷେପ ଦକ୍ଷତା ଯାତ୍ରା',
    step1: 'ମୋତେ ବୁଝନ୍ତୁ',
    step2: 'ମୋର ଦକ୍ଷତା ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ',
    step3: 'ମୋର ଅଭାବ ଚିହ୍ନଟ କରନ୍ତୁ',
    step4: 'ମୋର ଶିକ୍ଷଣ ପଥ ତିଆରି କରନ୍ତୁ',
    step5: 'ଶିଖନ୍ତୁ ଏବଂ ଅଭ୍ୟାସ କରନ୍ତୁ',
    step6: 'ନିରନ୍ତର ସୁଧାର କରନ୍ତୁ',
    greeting: 'ଶୁଭ ସକାଳ, ବଂଶୀ',
    dashboardOverview: 'ଏଠାରେ ଆପଣଙ୍କର ନିରନ୍ତର ଶିକ୍ଷା ଏବଂ ଦକ୍ଷତାର ସମୀକ୍ଷା ଅଛି।',
    competencyScore: 'ଦକ୍ଷତା ସ୍କୋର',
    skillReadiness: 'ଦକ୍ଷତା ପ୍ରସ୍ତୁତି',
    learningProgress: 'ଶିକ୍ଷଣ ପ୍ରଗତି',
    learningTime: 'ଶିକ୍ଷଣ ସମୟ',
    todaysLearning: 'ଆଜିର ଶିକ୍ଷା',
    todaysSkillByte: 'ଆଜିର ସ୍କିଲ୍ ବାଇଟ୍',
    skillDNA: 'ଆପଣଙ୍କର ସ୍କିଲ୍ DNA',
    careerReadiness: 'ଆପଣଙ୍କର ଦକ୍ଷତା ଆପଣଙ୍କୁ କେଉଁଠାକୁ ନେଇପାରିବ?',
    startLearning: 'ଶିଖିବା ଆରମ୍ଭ କରନ୍ତୁ',
    tryQuiz: 'କ୍ୱିଜ୍ ଚେଷ୍ଟା କରନ୍ତୁ',
    viewDetails: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    back: 'ଫେରନ୍ତୁ',
    save: 'ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ କରନ୍ତୁ',
    loading: 'ପ୍ରକ୍ରିୟା ଚାଲିଛି...',
  },
  pa: {
    govTitle: 'ਅੰਕੜਾ ਅਤੇ ਪ੍ਰੋਗਰਾਮ ਲਾਗੂਕਰਨ ਮੰਤਰਾਲਾ (MoSPI) • SIH ਪਹਿਲਕਦਮੀ',
    govSubtitle: 'ਭਾਰਤ ਅਧਿਕਾਰਤ ਅੰਕੜਾ ਪ੍ਰਣਾਲੀ (OSS) ਸਕਿਲ ਪਲੇਟਫਾਰਮ',
    platformName: 'ਸਟੈਟਪਾਥ AI',
    platformTagline: 'AI-ਸੰਚਾਲਿਤ ਸਕਿਲ ਇੰਟੈਲੀਜੈਂਸ ਅਤੇ ਲਰਨਿੰਗ ਪਲੇਟਫਾਰਮ',
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navAbout: 'ਸਾਡੇ ਬਾਰੇ',
    navHowItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    navEcosystem: 'ਲਰਨਿੰਗ ਈਕੋਸਿਸਟਮ',
    navCompetencies: 'ਯੋਗਤਾ ਦ੍ਰਿਸ਼',
    navSecurity: 'ਸੁਰੱਖਿਆ ਅਤੇ ਗੋਪਨੀਯਤਾ',
    navFaq: 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
    navLogin: 'ਅਧਿਕਾਰਤ ਲੌਗਇਨ',
    navRegister: 'ਸ਼ੁਰੂ ਕਰੋ',
    screenReader: 'ਸਕ੍ਰੀਨ ਰੀਡਰ',
    heroBadge: '🇮🇳 ਭਾਰਤ ਅਧਿਕਾਰਤ ਅੰਕੜਾ ਪ੍ਰਣਾਲੀ • ਮਿਸ਼ਨ ਕਰਮਯੋਗੀ',
    heroTitle: 'ਭਵਿੱਖ ਲਈ ਤਿਆਰ ਅੰਕੜਾ ਵਰਕਫੋਰਸ ਦਾ ਨਿਰਮਾਣ',
    heroSubhead: 'ਸਟੈਟਪਾਥ AI ਸਰਕਾਰੀ ਅਧਿਕਾਰੀਆਂ ਨੂੰ ਆਪਣੀਆਂ ਯੋਗਤਾਵਾਂ ਸਮਝਣ ਅਤੇ ਸਕਿਲ ਗੈਪਸ ਪਛਾਣਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
    heroCtaPrimary: 'ਸ਼ੁਰੂ ਕਰੋ',
    heroCtaSecondary: 'ਕਾਰਜਪ੍ਰਣਾਲੀ ਵੇਖੋ',
    whyTitle: 'ਸਟੈਟਪਾਥ AI ਕਿਉਂ?',
    traditionalLabel: 'ਰਵਾਇਤੀ ਸਿੱਖਿਆ',
    statpathLabel: 'ਸਟੈਟਪਾਥ AI ਨਿਰੰਤਰ ਇੰਟੈਲੀਜੈਂਸ',
    howTitle: '6-ਚਰਣ ਯੋਗਤਾ ਯਾਤਰਾ',
    step1: 'ਮੈਨੂੰ ਸਮਝੋ',
    step2: 'ਮੇਰੇ ਸਕਿਲਜ਼ ਦਾ ਮੁਲਾਂਕਣ ਕਰੋ',
    step3: 'ਮੇਰੀਆਂ ਕਮੀਆਂ ਪਛਾਣੋ',
    step4: 'ਮੇਰਾ ਲਰਨਿੰਗ ਪਾਥ ਬਣਾਓ',
    step5: 'ਸਿੱਖੋ ਅਤੇ ਅਭਿਆਸ ਕਰੋ',
    step6: 'ਨਿਰੰਤਰ ਸੁਧਾਰ ਕਰੋ',
    greeting: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ, ਵੰਸ਼ੀ',
    dashboardOverview: 'ਇੱਥੇ ਤੁਹਾਡੀ ਨਿਰੰਤਰ ਸਿੱਖਿਆ ਅਤੇ ਯੋਗਤਾ ਦਾ ਵੇਰਵਾ ਹੈ।',
    competencyScore: 'ਯੋਗਤਾ ਸਕੋਰ',
    skillReadiness: 'ਸਕਿਲ ਤਿਆਰੀ',
    learningProgress: 'ਲਰਨਿੰਗ ਪ੍ਰਗਤੀ',
    learningTime: 'ਲਰਨਿੰਗ ਸਮਾਂ',
    todaysLearning: 'ਅੱਜ ਦੀ ਸਿੱਖਿਆ',
    todaysSkillByte: 'ਅੱਜ ਦਾ ਸਕਿਲ ਬਾਈਟ',
    skillDNA: 'ਤੁਹਾਡਾ ਸਕਿਲ DNA',
    careerReadiness: 'ਤੁਹਾਡੇ ਸਕਿਲਜ਼ ਤੁਹਾਨੂੰ ਕਿੱਥੇ ਲੈ ਕੇ ਜਾ ਸਕਦੇ ਹਨ?',
    startLearning: 'ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ',
    tryQuiz: 'ਕੁਇਜ਼ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    back: 'ਵਾਪਸ',
    save: 'ਬਦਲਾਅ ਸੰਭਾਲੋ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [highContrast, setHighContrast] = useState<boolean>(false);
  const [fontSize, setFontSize] = useState<FontSize>('normal');

  useEffect(() => {
    // Restore language preference from localStorage
    const savedLang = localStorage.getItem('statpath_lang') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (newLang: Language) => {
    setLanguageState(newLang);
    localStorage.setItem('statpath_lang', newLang);
    changeModuleLanguage(newLang);
  };

  useEffect(() => {
    document.documentElement.setAttribute('data-contrast', highContrast ? 'high' : 'normal');
    document.documentElement.setAttribute('data-fontsize', fontSize);
    document.documentElement.setAttribute('lang', language);
  }, [highContrast, fontSize, language]);

  const toggleHighContrast = () => setHighContrast(prev => !prev);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, highContrast, toggleHighContrast, fontSize, setFontSize, t }}>
      <GoogleTranslator />
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
